### ISSUE TITLE
Example not updated

### ISSUE THREAD

**Issue by sh4nnongoh** [copercini/esp32-iot-examples#1]
Hi there!

The exposed functions in your WifiClientSecure.h don't fit the ones used in this example.
Is this example code updated?

**Comment by copercini** [comment]
Hi!

which functions don't fit ?
Do you have installed this lib too https://github.com/256dpi/arduino-mqtt ? Some functions are used from this library...

**Comment by pherris** [comment]
I believe he is referring to `setCACert`

**Comment by karanmilan** [comment]
No, it doesn't solve the issue. The library is different

**Comment by BartIOT** [comment]
The WifiClientSecure.cpp library is not compatible. The call to net.setCACert(rootCABuff) does not match the library routine:    bool WiFiClientSecure::setCACert(const uint8_t* pk, size_t size).

Which library are you using?

**Comment by copercini** [comment]
I don't understand, for me it's `void setCACert(const char *rootCA);` 
https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFiClientSecure/src/WiFiClientSecure.h#L60

**Comment by BartIOT** [comment]
I was using the esp8266 libraries not esp32 libraries. Now that I changed to the esp32 libraries that error is gone but now I get:

`sketch\ssl_client.h:7:30: fatal error: mbedtls/platform.h: No such file or directory
 #include "mbedtls/platform.h"`

I've found several sources for the mbedtls library. Is there a specific one I should use?

Thanks for the assist.

**Comment by copercini** [comment]
@BartIOT take a look on this https://github.com/copercini/esp8266-aws_iot/tree/working

It's a updated version of example to ESP8266 and should works (but I not have a board to test it right now)
