### ISSUE TITLE
Guru Meditation error 

### ISSUE THREAD

**Issue by preetampds** [copercini/esp32-iot-examples#2]
Hi,
I am using sparkfun ESP32. Created the thing in aws iot, certificates created and ported to sketch. after uploading 
i get the below error

load:0x3fff0008,len:8
load:0x3fff0010,len:1848
load:0x40078000,len:6712
load:0x40080000,len:252
entry 0x40080034
Checking wifi.....
                  connecting...Free heap before TLS 107872

Connect to Server failed!
Free heap after TLS 107140
MbedTLS error -28928mbedtls_ssl_write returned -0x7100

Cleaning SSL connection.
Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
Register dump:
PC      : 0x400f4514  PS      : 0x00060430  A0      : 0x800fbabd  A1      : 0x3ffdd350
A2      : 0x3ffc8554  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000000
A6      : 0x00000004  A7      : 0xff000000  A8      : 0x0841b846  A9      : 0x3ffdd340
A10     : 0x3ffc81d0  A11     : 0x00000000  A12     : 0x00000050  A13     : 0x3ffc8220
A14     : 0x00000000  A15     : 0x00000005  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0841b86e  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000

Backtrace: 0x400f4514:0x3ffdd350 0x400fbabd:0x3ffdd370 0x400d16d1:0x3ffdd390 0x400d1560:0x3ffdd3b0 0x400d1540:0x3ffdd3d0 0x400d2494:0x3ffdd3f0 0x400d1fb8:0x3ffdd410 0x400d22a5:0x3ffdd430 0x400d2311:0x3ffdd460 0x400d1370:0x3ffdd480 0x400d13fa:0x3ffdd4a0 0x4012a282:0x3ffdd4c0

CPU halted.

**Comment by copercini** [comment]
sorry for late answer, please decode the backtrace with https://github.com/me-no-dev/EspExceptionDecoder

**Comment by copercini** [comment]
Please, check it now with last ESP32 core.
