### ISSUE TITLE
WiFi_portal.ino content of Preferences.h

### ISSUE THREAD

**Issue by mikekgr** [copercini/esp32-iot-examples#3]
Dear Sir,
I am looking at your fine WiFi_portal.ino example, but I am not sure what should the content for Preferences.h 
Can you give me an example?

Thanks and Best Regards,
Mike Kranidis

**Comment by copercini** [comment]
Preferences.h is a default library from Arduino ESP32 core. You can have it updating your core version to the last: https://github.com/espressif/arduino-esp32/blob/master/doc/windows.md#how-to-update-to-the-latest-code

The contend inside it will be your **ssid** and **password** after you open the portal and insert it into

**Comment by mikekgr** [comment]
Dear frient,
I am not very experienced with the ESP32 Core but I have updated. 
When I am trying to compile your example, I am gettig the following errors:
E:\ARDUINO_ESP_DEV\arduino-1.8.3\portable\sketchbook\WiFi_portal.ino\WiFi_portal.ino.ino: In function 'void wifiOnDisconnect()':

WiFi_portal.ino:122: error: 'wifiSSID' was not declared in this scope

   WiFi.begin(wifiSSID.c_str(), wifiPassword.c_str());

              ^

WiFi_portal.ino:122: error: 'wifiPassword' was not declared in this scope

   WiFi.begin(wifiSSID.c_str(), wifiPassword.c_str());

                                ^

Multiple libraries were found for "WiFi.h"
 Used: E:\ARDUINO_ESP_DEV\arduino-1.8.3\hardware\espressif\esp32\libraries\WiFi
 Not used: E:\ARDUINO_ESP_DEV\arduino-1.8.3\libraries\WiFi
exit status 1
'wifiSSID' was not declared in this scope

Does make any sense to you?
Again thanks!

**Comment by copercini** [comment]
I can confirm this bug
Please, test this: https://github.com/copercini/esp32-iot-examples/blob/WiFi_portal_fix/WiFi_portal/WiFi_portal.ino

**Comment by mikekgr** [comment]
Yes, the above version can be complied without any problem.
Thanks a lot for your fine support!

**Comment by copercini** [comment]
Fixed!
