### ISSUE TITLE
Porting to Feather WICED

### ISSUE THREAD

**Issue by rautmithil** [copercini/esp32-iot-examples#5]
I am looking to run this code on a Feather WICED. It gives me an error for preferences.h file. If I understand this correctly, can I substitute the functions of Preferences.h with some other library?

**Comment by copercini** [comment]
preferences.h is just to store your WiFi credentials in the chip, I don't know much about Feather WICED but looks like the most close thing available is write it on the flash memory, here is an example of how write files in the flash storage: https://github.com/adafruit/Adafruit_WICED_Arduino/blob/master/libraries/AdafruitWicedExamples/SPIFLASH/spiflash_writefile/spiflash_writefile.ino

**Comment by rautmithil** [comment]
Thanks for the reference, I'll try this.
